# version: '3.8'
services:
  app:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:docker@localhost:5437/sistema_cadastro_cliente?schema=public

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sistema_cadastro_cliente
    ports:
      - "5437:5432"

volumes:
  pgdata: