name: "Deploy para VPS"
on: 
  push: 
    branches:
     - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
       - name: "Commands to update in VPS"
         uses: appleboy/ssh-action@v1.0.3
         with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.USERNAME }}
             password: ${{ secrets.PASSWORD }}
             script:  |
               cd /root/AuthSystem
               git pull
               npm i
               pm2 update