name: "Deploy para VPS"
on: 
  push: 
    branches:
     - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
       - name: "Baixar o código"
         uses: actions/checkout@v4

       - name: "Copiar arquivos para VPS"
         uses: appleboy/scp-actions@v0.1.7
         with:
           host: ${{ secrets.HOST }}
           username:  ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.PORT }}
           source: "."
           target: "/AuthSystem"

       - name: "Build da aplicacao"
         uses: aplleboy/ssh-actions@v1.0.3
         with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.USERNAME }}
             key: ${{ secrets.SSH_PRIVATE_KEY }}
             script:  |
               cd /AuthSystem
               docker-compose down
               docker-compose up -d --build
               docker-compose exec app npx prisma migrate deploy